package com.aipa.agent.adapter;

import com.aipa.agent.AIAdapter;
import com.aipa.agent.AIRequest;
import com.aipa.agent.AIResponse;
import com.aipa.agent.AdapterType;
import org.springframework.stereotype.Component;

/** Phase 4 最小實作 — Ollama Adapter（本地 deterministic fallback） */
@Component
public class OllamaAdapter implements AIAdapter {
    @Override public String name() { return "Ollama"; }
    @Override public AdapterType type() { return AdapterType.OLLAMA; }
    @Override public boolean isAvailable() { return true; }

    @Override
    public AIResponse generate(AIRequest request) {
        String content = "// AI Draft generated by Ollama adapter\n"
                + "// Requirement: " + request.taskSpec() + "\n"
                + "// Knowledge Context Summary:\n"
                + (request.contextKnowledge().isBlank() ? "// - none\n" : "// - " + request.contextKnowledge().replace("\n", "\n// - ") + "\n")
                + "public class GeneratedChangePlan {\n"
                + "    public String summary() {\n"
                + "        return \"" + escape(request.taskSpec()) + "\";\n"
                + "    }\n"
                + "}\n";
        return new AIResponse(content, "ollama", "local-simulated", estimateTokens(request.taskSpec()), estimateTokens(content), 35, true, "");
    }

    @Override public int estimateTokens(String text) { return Math.max(1, text.length() / 4); }

    private String escape(String text) {
        return text.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
