package com.aipa.runtime.service;

import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

@Service
public class GitService {

    public Map<String, Object> createPrPreview(String requirement, String provider, String sessionId) {
        String normalizedRequirement = requirement == null ? "change" : requirement.trim();
        if (normalizedRequirement.isEmpty()) {
            normalizedRequirement = "change";
        }
        String branch = "aipa/feature/" + Integer.toHexString((sessionId + normalizedRequirement).hashCode());
        String commitId = UUID.randomUUID().toString().replace("-", "").substring(0, 12);
        String prUrl = "https://example.local/aipa/pull/" + Integer.toHexString((branch + provider).hashCode());

        return Map.of(
                "title", "feat: " + normalizedRequirement,
                "description", "Generated by Phase 4 pipeline using provider " + provider,
                "branch", branch,
                "commitId", commitId,
                "prUrl", prUrl,
                "generatedAt", Instant.now().toString()
        );
    }
}

